parameters:
#    jonaguera_ono_scraper.example.class: Jonaguera\OnoScraperBundle\Example

services:
#    jonaguera_ono_scraper.example:
#        class: %jonaguera_ono_scraper.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
